#!/bin/bash

echo "🔍 Complete Guide: How to Search Traces in Jaeger"
echo "================================================="
echo ""
echo "📍 Current Status:"
echo "   • Jaeger UI: http://localhost:16686"
echo "   • Liberty Server: http://localhost:9080"
echo "   • Payment Service: Running (telemetry config being applied)"
echo ""

echo "🎯 JAEGER SEARCH INTERFACE GUIDE"
echo "================================="
echo ""
echo "1. 📋 BASIC SEARCH PANEL (Left Side)"
echo "   ├── Service: Select which service to view traces from"
echo "   ├── Operation: Filter by specific endpoints/methods"
echo "   ├── Tags: Search by key:value pairs"
echo "   ├── Lookback: Time range (15m, 1h, 6h, 1d, etc.)"
echo "   ├── Min/Max Duration: Filter by trace duration"
echo "   └── Limit Results: Number of traces to show"
echo ""

echo "2. 🔎 SEARCH STRATEGIES"
echo ""
echo "   📌 BASIC SERVICE SEARCH:"
echo "   Service: payment-service"
echo "   → Click 'Find Traces'"
echo "   → Shows all traces from payment service"
echo ""

echo "   📌 OPERATION-SPECIFIC SEARCH:"
echo "   Service: payment-service"
echo "   Operation: processPayment"
echo "   → Shows only traces from specific method"
echo ""

echo "   📌 TAG-BASED SEARCHES:"
echo "   Service: payment-service"
echo "   Tags: payment.amount:99.99"
echo "   → Find traces for specific payment amounts"
echo ""
echo "   Tags: http.method:POST"
echo "   → Find all POST requests"
echo ""
echo "   Tags: error:true"
echo "   → Find only failed operations"
echo ""
echo "   Tags: payment.currency:USD"
echo "   → Find USD transactions only"
echo ""

echo "   📌 DURATION-BASED SEARCHES:"
echo "   Service: payment-service"
echo "   Min Duration: 2s"
echo "   → Find slow operations (> 2 seconds)"
echo ""
echo "   Max Duration: 500ms"
echo "   → Find fast operations (< 500ms)"
echo ""

echo "   📌 TIME-BASED SEARCHES:"
echo "   Lookback: Last 15m"
echo "   → Recent traces only"
echo ""
echo "   Custom time range:"
echo "   Start Time: 2025-06-02 10:00:00"
echo "   End Time: 2025-06-02 11:00:00"
echo ""

echo "3. 🏷️ AVAILABLE SEARCH TAGS (When Working)"
echo ""
echo "   💳 Payment Tags:"
echo "   • payment.amount:75.50"
echo "   • payment.currency:USD"
echo "   • payment.cardNumber.masked:****1111"
echo "   • payment.merchantId:AMAZON_STORE"
echo "   • transaction.id:TXN-12345"
echo ""
echo "   🔒 Process Tags:"
echo "   • fraud.check.result:FRAUD_DETECTED"
echo "   • funds.availability:INSUFFICIENT"
echo "   • validation.result:FAILED"
echo "   • payment.gateway.endpoint:gateway-url"
echo ""
echo "   🚨 Error Tags:"
echo "   • error:true"
echo "   • error.message:timeout"
echo "   • http.status_code:500"
echo ""

echo "4. 📊 UNDERSTANDING SEARCH RESULTS"
echo ""
echo "   📈 Result Table Columns:"
echo "   ├── Trace ID: Unique identifier (click to view details)"
echo "   ├── Root Span: Main operation name"
echo "   ├── Duration: Total time for entire trace"
echo "   ├── Services: Number of services involved"
echo "   ├── Depth: Number of span levels"
echo "   ├── Total Spans: Total operations in trace"
echo "   └── Start Time: When trace began"
echo ""
echo "   🎨 Color Coding:"
echo "   • Blue: Successful operations"
echo "   • Red: Operations with errors"
echo "   • Orange: Operations with warnings"
echo ""

echo "5. 🔍 ADVANCED SEARCH TECHNIQUES"
echo ""
echo "   🎯 Complex Queries (JSON Mode):"
echo "   Click 'JSON' button for advanced queries:"
echo '   {'
echo '     "service": "payment-service",'
echo '     "tags": {'
echo '       "payment.amount": {"$gte": 100, "$lte": 500},'
echo '       "http.method": "POST"'
echo '     }'
echo '   }'
echo ""

echo "   📈 Performance Analysis:"
echo "   • Compare successful vs failed payments"
echo "   • Identify bottlenecks in payment processing"
echo "   • Track retry patterns"
echo "   • Monitor fraud detection timing"
echo ""

echo "   🔗 Trace Correlation:"
echo "   • Follow requests across microservices"
echo "   • Track payment flow from start to finish"
echo "   • Identify service dependencies"
echo ""

echo "6. 🛠️ PRACTICAL SEARCH EXAMPLES"
echo ""
echo "   💰 Business Scenarios:"
echo ""
echo "   Find high-value transactions:"
echo "   Tags: payment.amount:>=1000"
echo ""
echo "   Find fraud attempts:"
echo "   Tags: payment.cardNumber.masked:****0000"
echo ""
echo "   Find specific merchant transactions:"
echo "   Tags: payment.merchantId:AMAZON_STORE"
echo ""
echo "   Find international payments:"
echo "   Tags: payment.currency:EUR"
echo ""

echo "   🐛 Debugging Scenarios:"
echo ""
echo "   Find timeout errors:"
echo "   Tags: error.message:timeout"
echo ""
echo "   Find validation failures:"
echo "   Tags: validation.result:FAILED"
echo ""
echo "   Find retry attempts:"
echo "   Operation: processPayment"
echo "   Tags: retry.attempt:>1"
echo ""

echo "7. 💡 SEARCH BEST PRACTICES"
echo ""
echo "   🎯 Search Strategy:"
echo "   1. Start broad (service only)"
echo "   2. Add time constraints"
echo "   3. Include specific operations"
echo "   4. Apply business logic filters"
echo "   5. Refine with tags"
echo ""
echo "   ⚡ Performance Tips:"
echo "   • Use specific time ranges"
echo "   • Limit result count for large datasets"
echo "   • Combine multiple criteria"
echo "   • Save frequently used searches"
echo ""

echo "8. 🔧 TROUBLESHOOTING SEARCHES"
echo ""
echo "   ❌ No Results Found?"
echo "   • Check service name spelling"
echo "   • Verify time range"
echo "   • Ensure tags use correct syntax"
echo "   • Try broader search first"
echo ""
echo "   📊 Too Many Results?"
echo "   • Narrow time window"
echo "   • Add operation filters"
echo "   • Include specific tags"
echo "   • Increase minimum duration"
echo ""

echo "9. 📚 NEXT STEPS"
echo ""
echo "   Once traces appear in Jaeger:"
echo "   • Click on traces to see detailed timeline"
echo "   • Analyze span relationships"
echo "   • Export traces for reporting"
echo "   • Set up alerts based on patterns"
echo "   • Create dashboards for monitoring"
echo ""

echo "🎯 QUICK REFERENCE:"
echo "==================="
echo "Basic Search: Service + Find Traces"
echo "Filter by Tags: key:value format"
echo "Time Range: Use Lookback dropdown"
echo "Performance: Min/Max Duration"
echo "Advanced: Click JSON for complex queries"
echo ""
echo "🌟 Remember: Click any trace in results to see detailed view!"
echo ""
