# microprofile-config.properties
mp.openapi.scan=true
product.maintenanceMode=false

# Payment Service Configuration

# Service URLs
order.service.url=http://localhost:8050/order
user.service.url=http://localhost:6050/user